"""empty message

Revision ID: a5e3a5c90948
Revises: e9e556fd22f2
Create Date: 2022-11-28 12:03:46.247913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e3a5c90948'
down_revision = 'e9e556fd22f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('precipitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kenn', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('start_measure', sa.String(), nullable=True),
    sa.Column('end_measure', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('precipitations')
    # ### end Alembic commands ###
