"""empty message

Revision ID: e9e556fd22f2
Revises: 1b02351db064
Create Date: 2022-11-18 13:54:15.345526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e556fd22f2'
down_revision = '1b02351db064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ODL',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kenn', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('start_measure', sa.String(), nullable=True),
    sa.Column('end_measure', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ODL')
    # ### end Alembic commands ###
